name: marksutor
favicon: null
layout_spectrum: 0.8939347793348134
typography_spectrum: 0.78784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9713e'
    - '#1e0000'
    - '#552c13'
    - '#65642a'
  brandStrength: 0.43306199624203146
  lightness: 0.5050027708057314
  saturation: 0.7961443229578435
  rhythmicContrast: 0.05413616495206952
purpose: []
